version: '2'

services:
  # agile-example:
  #   build: apps/agile-example
  #   ports:
  #    - 80:80/tcp

  agile-dbus:
    container_name: agile-dbus
    image: agileiot/agile-dbus-armv7l
    # build: apps/agile-dbus
    restart: always
    volumes:
      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus

  agile-core:
    container_name: agile-core
    image: agileiot/agile-core-armv7l
    # build: apps/agile-core
    depends_on:
      - agile-dbus
    volumes:
      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
    ports:
      - 8080:8080/tcp
    restart: always
    privileged: true
    command: bash -c "scripts/start.sh DeviceManager & scripts/start.sh ProtocolManager & scripts/start.sh http"

  agile-ble:
    container_name: agile-ble
    image: agileiot/agile-ble-armv7l
    # build: apps/agile-core
    depends_on:
      - agile-dbus
    volumes:
      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
    environment:
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
    restart: always
    privileged: true
    network_mode: "host"
    command: bash -c "mkdir -p /var/run/dbus && rm -f /var/run/dbus/pid && dbus-daemon --system && hciconfig hci0 down && hciconfig hci0 up && /usr/local/libexec/bluetooth/bluetoothd -E & scripts/start.sh BLE"

  agile-ui:
    container_name: agile-ui
    image: agileiot/agile-ui-armv7l:v0.1.1
    # build: apps/agile-ui
    restart: always
    depends_on:
      - agile-core
    ports:
      - 2000:1337/tcp

  agile-osjs:
    container_name: agile-osjs
    image: agileiot/agile-osjs-armv7l
    # build: apps/agile-osjs
    depends_on:
      - agile-core
    ports:
      - 8000:8000/tcp
    restart: always

  agile-nodered:
    container_name: agile-nodered
    image: agileiot/agile-nodered-armv7l
    # build: apps/agile-nodered
    hostname: agile-nodered
    volumes:
      - $DATA/nodered:/root/.node-red
    ports:
      - 1880:1880/tcp
    links:
      - agile-core:agile
    restart: always

#  agile-zb:
#    container_name: agile-zb
#    image: agileiot/agile-zb-armv7l
#    # build: apps/agile-zb
#    depends_on:
#      - agile-dbus
#    devices:
#      - dev/ttyUSB0:/dev/ttyUSB0
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#    environment:
#      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
#    command: python3 dbus_server/dbus_server.py

#  agile-zb-lamp:
#    container_name: agile-zb-lamp
#    image: agileiot/agile-zb-armv7l
#    depends_on:
#      - agile-zb
#    volumes:
#      - $DBUS_SESSION_SOCKET_DIR:/usr/src/app/.agile_bus
#    environment:
#      - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/.agile_bus/agile_bus_socket
#    command: python3 ge_link_bulb/ge_link_bulb_device.py
